version: '3.9'
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=url
    volumes:
      - ./url.sql:/docker-entrypoint-initdb.d/url.sql
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=url
      - DB_SSL=disable
      - DB_PASSWORD=qwerty
    depends_on:
      - postgres